### PR TITLE
Nrf fqdn

### PR DESCRIPTION
**Pull request by thinhnt1983**
- Add 5G features with NRF and FQDN support

### CODE REVIEW

**Review by rdefosse — COMMENTED** [review]
@thinhnt1983 @lionelgo 

I will approve from a CI point of view.

But still I think there is a problem of `boost` version on the `U18` target image.

I will try again this afternoon

**Review by rdefosse — COMMENTED** [review]
@lionelgo @thinhnt1983 

push a better installation of `boost` on Ubuntu

Let see how it goes

**Review by rdefosse — APPROVED** [review]
@lionelgo @thinhnt1983 

I approve from a CI point of view.

I've checked the `Ubuntu18` target image is now really using `boost-system-1.67`

@thinhnt1983 

can you check in 5G mode to see if it is OK?

**Comment by thinhnt1983** [comment]
Thanks @rdefosse, i'll check it and let you know the outcome later.

**Comment by rdefosse** [comment]
@thinhnt1983 

before we merge, could you please have a better description of the pull request?

And maybe we need to update `docs/FEATURE_SET,md`.

I will update `CHANGELOG.md` accordingly

**Comment by rdefosse** [comment]
It also passed the CN5G FED pipeline `https://jenkins-oai.eurecom.fr/job/OAI-CN5G-FED/236/`

**Pull request merged**
